In [3]:
#DET
print(f'A= \n{A}') 

def ryDet(A): 

    n= A.shape[0] 
    if n>1: 
        i= 0 

        Bi=  np.delete(A, i, axis=0) 

        #print(f'\ni= {i}, Bi= \n{Bi}') 

        det= 0 

        for j in range(n): 

            Bij= np.delete(Bi,j, axis=1) 

            print(f'\ni,j= {i}{j}, Bij= \n{Bij}')            

            Dij= ryDet(Bij) #np.linalg.det(Bij) 

            print(f'.... Dij= {Dij}')             

            Cij= A[i,j]*Dij*(-1)**(i+j) 

            det += Cij 

        #print(f'det= {det}') 

        return det     

    elif A.shape[0]==1: 

        det= A[0,0] 

        return det 

    else: 

        return None 

det= ryDet(A) 

print(f'\ndet= {det}')

A= 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

i,j= 00, Bij= 
[[ 6  7  8  9]
 [11 12 13 14]]

i,j= 00, Bij= 
[[12 13 14]]
.... Dij= 12

i,j= 01, Bij= 
[[11 13 14]]
.... Dij= 11
.... Dij= -5

i,j= 01, Bij= 
[[ 5  7  8  9]
 [10 12 13 14]]

i,j= 00, Bij= 
[[12 13 14]]
.... Dij= 12

i,j= 01, Bij= 
[[10 13 14]]
.... Dij= 10
.... Dij= -10

i,j= 02, Bij= 
[[ 5  6  8  9]
 [10 11 13 14]]

i,j= 00, Bij= 
[[11 13 14]]
.... Dij= 11

i,j= 01, Bij= 
[[10 13 14]]
.... Dij= 10
.... Dij= -5

det= 0


In [4]:
import os
import sys
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
%precision 4
plt.style.use('ggplot')

In [5]:
#LU Decomposition
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
print(P)
print(L)
print(U)

[[1 3 4]
 [2 1 3]
 [4 1 2]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.     0.     0.    ]
 [0.25   1.     0.    ]
 [0.5    0.1818 1.    ]]
[[4.     1.     2.    ]
 [0.     2.75   3.5   ]
 [0.     0.     1.3636]]


In [6]:
#特徵向量(Eigenvector)
A = np.array([[0,1,1],[2,1,0],[3,4,5]])

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0.+0.j  1.+0.j  1.+0.j]
 [ 2.+0.j  1.+0.j -0.+0.j]
 [ 3.+0.j  4.+0.j  5.+0.j]]
[ 5.8541+0.j -0.8541+0.j  1.    +0.j]


In [7]:
A = np.array([[0,1],[-1,0]])
print(A)

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0  1]
 [-1  0]]
[[ 0.+0.j  1.+0.j]
 [-1.+0.j  0.+0.j]]
[0.+1.j 0.-1.j]


In [8]:
# If you know the eigenvalues must be real
# because A is a positive definite (e.g. covariance) matrix
# use real_if_close

A = np.array([[0,1,1],[2,1,0],[3,4,5]])
u, V = la.eig(A)
print(u)
print (np.real_if_close(u))

[ 5.8541+0.j -0.8541+0.j  1.    +0.j]
[ 5.8541 -0.8541  1.    ]


In [9]:
#Stabilty
A = np.array([[8,6,4,1],[1,4,5,1],[8,4,1,1],[1,4,3,6]])
b = np.array([19,11,14,14])
la.solve(A,b)

array([1., 1., 1., 1.])

In [10]:
b = np.array([19.01,11.05,14.07,14.05])
la.solve(A,b)
#Note that the tiny perturbations in the outcome vector b cause large differences in the solution! 
#When this happens, we say that the matrix A ill-conditioned. 
#This happens when a matrix is ‘close’ to being singular (i.e. non-invertible)

array([-2.34 ,  9.745, -4.85 , -1.34 ])

In [11]:
#Condition Number

U, s, V = np.linalg.svd(A)
print(s)
print(max(s)/min(s))

[15.5457  6.9002  3.8363  0.0049]
3198.6725811991305


In [12]:
#1. Compute the LU decomposition of the following matrix by hand and using numpy
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
print(P)
print(L)
print(U)

[[ 1  2  3]
 [ 2 -4  6]
 [ 3 -9 -3]]
[[ 3. -9. -3.]
 [ 1.  2.  3.]
 [ 2. -4.  6.]]
[[ 3. -9. -3.]
 [ 1.  2.  3.]
 [ 2. -4.  6.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.     0.     0.    ]
 [0.3333 1.     0.    ]
 [0.6667 0.4    1.    ]]
[[ 3.  -9.  -3. ]
 [ 0.   5.   4. ]
 [ 0.   0.   6.4]]


In [13]:
#2. Compute the Cholesky decomposition of the following matrix by hand and using numpy
A = np.array([[1,3,5],[3,13,23],[5,23,42]])
L = np.linalg.cholesky(A)
#U = la.cholesky(A)
print(np.dot(L.T, L))

print(L)
print(A)
#holesky decomposition is about twice as fast as LU decomposition (though both scale as n3)

[[35. 26.  5.]
 [26. 20.  4.]
 [ 5.  4.  1.]]
[[1. 0. 0.]
 [3. 2. 0.]
 [5. 4. 1.]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 42]]


In [14]:
#3. Write a function in Python to solve a system
#Ax=b
#using SVD decomposition. Your function should take A and b as input and return x.
def svdsolver(A,b):
    U, s, V = np.linalg.svd(A)
    if np.prod(s) == 0:
        print("Matrix is singular")
    else:
        return np.dot(np.dot((V.T).dot(np.diag(s**(-1))), U.T),b)

In [15]:
A = np.array([[1,1],[1,2]])
b = np.array([3,1])
print(np.linalg.solve(A,b))
print(svdsolver(A,b))

[ 5. -2.]
[ 5. -2.]
